#!/usr/bin/env bash

# Version:  0.01_4311
# NOTE:  Make sure the "openssl" binary is in your $PATH

server="$1"
port="$2"
port=${port:-443}

for v in ssl2 ssl3 tls1 tls1_1 tls1_2 tls1_3
do
    for c in $(openssl ciphers 'ALL:eNULL' | tr ':' ' ')
    do
        openssl s_client -connect "${server}:${port}" -cipher $c -$v < /dev/null > /dev/null 2>&1 
        if [ $? -eq 0 ] 
        then
            echo -e "$v:\t$c YES"
        else
            echo -e "$v:\t$c NO"
        fi
    done
done

#
# Based on script from
# https://www.ise.io/using-openssl-determine-ciphers-enabled-server/
# Original code is:
# Copyright <2015> <INDEPENDENT SECURITY EVALUATORS>
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


